FROM python:3.8
# set working directory RUN mkdir -p /usr/src/app WORKDIR /usr/src/app
# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
# install requirements
WORKDIR /usr/src/app/
RUN pip install -r requirements.txt
# add app
COPY . /usr/src/app
# run server
CMD python manage.py run -h 0.0.0.0